# Use an official Python runtime as a parent image
FROM python:3.13-rc-bookworm

# Set the working directory to /app
WORKDIR /src

# Copy the current directory contents into the container at /app

COPY . /src

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r dev_requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

RUN ls
# Define environment variable
ENV FLASK_APP app

# Run app.py when the container launches
ENTRYPOINT ["tail", "-f", "/dev/null"]
#CMD ["python", "-m", "flask", "run"]
